-- Ejercicio 1

DROP TABLE TB_OBJETOS;

CREATE TABLE TB_OBJETOS (
    NOMBRE VARCHAR2(128),
    CODIGO NUMBER PRIMARY KEY,
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    TIPO VARCHAR2(128),
    ESQUEMA_ORIGINAL VARCHAR2(128)
);

SELECT * FROM ALL_OBJECTS;

DECLARE 
    CURSOR C_OBJECTS IS
        SELECT OBJECT_NAME, OBJECT_ID, CREATED, LAST_DDL_TIME, OBJECT_TYPE, OWNER
        FROM ALL_OBJECTS;
BEGIN
    FOR OBJ IN C_OBJECTS LOOP
        INSERT INTO TB_OBJETOS (NOMBRE, CODIGO, FECHA_CREACION, FECHA_MODIFICACION, TIPO, ESQUEMA_ORIGINAL)
        VALUES(OBJ.OBJECT_NAME, OBJ.OBJECT_ID, OBJ.CREATED, OBJ.LAST_DDL_TIME, OBJ.OBJECT_TYPE, OBJ.OWNER);
    END LOOP;
    COMMIT;
END;
/

-- Ejercicio 2

DROP TABLE TB_ESTILO;

CREATE TABLE TB_ESTILO (
    TIPO_OBJETO VARCHAR2(128) PRIMARY KEY,
    PREFIJO VARCHAR(128)
);

INSERT INTO TB_ESTILO VALUES('PROCEDURE', 'PR_');
INSERT INTO TB_ESTILO VALUES('FUNCTION', 'FN_');
INSERT INTO TB_ESTILO VALUES('PACKAGE', 'PK_');
INSERT INTO TB_ESTILO VALUES('TABLE', 'TB_');
INSERT INTO TB_ESTILO VALUES('VIEW', 'VW_');
INSERT INTO TB_ESTILO VALUES('TRIGGER', 'TR_');
INSERT INTO TB_ESTILO VALUES('SYNONYM', 'SYN_');
INSERT INTO TB_ESTILO VALUES('INDEX', 'IND_');
COMMIT;

-- Ejercicio 3

ALTER TABLE TB_OBJETOS ADD (
    ESTADO VARCHAR2(128),
    NOMBRE_CORRECTO VARCHAR2(128)
);

CREATE OR REPLACE PROCEDURE PR_COMPROBAR(ESQUEMA IN VARCHAR2 DEFAULT NULL) IS
    CURSOR C_OBJECTS IS
        SELECT NOMBRE, TIPO, ESQUEMA_ORIGINAL
        FROM TB_OBJETOS
        WHERE UPPER(ESQUEMA_ORIGINAL) = NVL(UPPER(ESQUEMA), UPPER(ESQUEMA_ORIGINAL))
        FOR UPDATE;

    V_ESTADO VARCHAR2(128);
    V_NOMBRE VARCHAR2(128);
    V_PREFIJO VARCHAR2(128);
BEGIN
    FOR OBJ IN C_OBJECTS LOOP
        V_PREFIJO := NULL;

        BEGIN
            SELECT PREFIJO INTO V_PREFIJO
            FROM TB_ESTILO
            WHERE UPPER(TIPO_OBJETO) = UPPER(OBJ.TIPO);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_PREFIJO := NULL;
        END;

        IF V_PREFIJO IS NULL THEN
            V_ESTADO := 'SIN REGLA';
            V_NOMBRE := OBJ.NOMBRE;
        ELSIF UPPER(OBJ.NOMBRE) LIKE UPPER(V_PREFIJO) || '%' THEN
            V_ESTADO := 'CORRECTO';
            V_NOMBRE := OBJ.NOMBRE;
        ELSE
            V_ESTADO := 'INCORRECTO';
            V_NOMBRE := SUBSTR(V_PREFIJO || OBJ.NOMBRE, 1, 128);
        END IF;

        UPDATE TB_OBJETOS
        SET ESTADO = V_ESTADO, 
            NOMBRE_CORRECTO = V_NOMBRE
        WHERE CURRENT OF C_OBJECTS;
    END LOOP;
    COMMIT;
END;
/

EXECUTE PR_COMPROBAR();

SELECT COUNT(*), ESTADO FROM TB_OBJETOS GROUP BY ESTADO;