services:
  db:
    image: "mysql:8.4.0"
    container_name: db_tareas
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tareas
      - MYSQL_USER=desarrollador
      - MYSQL_PASSWORD=1234
    volumes:
      - "db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "desarrollador", "-p1234"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tareas
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  
  frontend:
    image: httpd:alpine
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./frontend/index.html:/usr/local/apache2/htdocs/index.html"

volumes:
  db:
