-- 1
CREATE TABLE CATEGORIA (
    ID NUMBER, 
    NOMBRE_CATEGORIA VARCHAR2(50 BYTE),
    IVA NUMBER(5,2)
)
TABLESPACE TS_EXAMEN19
PCTFREE 5;

-- 2
create table PRODUCTO(
    CODIGO_BARRAS NUMBER,
    OFERTA NUMBER,
    DESCRIPCION VARCHAR2(500 CHAR),
    STOCK NUMBER,
    EXPOSICION NUMBER,
    TEMPERATURA NUMBER,
    PESO_NETO NUMBER,
    CATEGORIA NUMBER,
    METROS_LINEALES NUMBER,
    PRECIO_ACTUAL NUMBER(6,2),
    PASILLO NUMBER
)
TABLESPACE TS_EXAMEN19
PCTFREE 15;

-- 3
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_BARRAS);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID);

-- 4
CREATE BITMAP INDEX IDX_PRODUCTO_CATEGORIA ON PRODUCTO(CATEGORIA);
CREATE INDEX IDX_PRODUCTO_DESCRIPCION ON PRODUCTO(UPPER(DESCRIPCION));
CREATE INDEX ID_PRODUCTO_PRECIO ON PRODUCTO(PRECIO);
CREATE UNIQUE INDEX IDX_CATEGORIA_NOMBRE ON CATEGORIA(NOMBRE_CATEGORIA);

-- 5
GRANT SELECT ON CATEGORIA TO R_CORRIGE;
GRANT UPDATE (NOMBRE_CATEGORIA) ON CATEGORIA TO R_CORRIGE;
CREATE VIEW VW_PRODUCTO AS SELECT CODIGO_BARRAS, DESCRIPCION, CATEGORIA, PRECIO_ACTUAL FROM PRODUCTO;
GRANT SELECT ON VW_PRODUCTO TO R_CORRIGE;

-- 6
CREATE SYNONYM CATEGORY FOR CATEGORIA;
CREATE SYNONYM PRODUCT FOR PRODUCTO;

-- 7
SELECT * FROM ALL_USERS;
INSERT INTO ABD1.MI_RESPUESTA VALUES (1, '23/06/26');

SELECT * FROM DICT WHERE TABLE_NAME LIKE '%PRIVS%';
SHOW SGA;
INSERT INTO ABD1.MI_RESPUESTA VALUES (2, 318767104);

SELECT * FROM V$DATAFILE;
INSERT INTO ABD1.MI_RESPUESTA VALUES (3, 12800);

SELECT * FROM V$LOG;
INSERT INTO ABD1.MI_RESPUESTA VALUES (4, 209715200);

SELECT * FROM USER_SYS_PRIVS UNION SELECT * FROM ROLE_SYS_PRIVS;
INSERT INTO ABD1.MI_RESPUESTA VALUES (5, 'CREATE SESSION');

-- 8
DROP MATERIALIZED VIEW VM_PRODUCTO;
CREATE MATERIALIZED VIEW VM_PRODUCTO
REFRESH NEXT SYSDATE + 1/24
AS SELECT CODIGO_BARRAS, DESCRIPCION, STOCK, NOMBRE_CATEGORIA, PRECIO_ACTUAL + (PRECIO_ACTUAL * IVA/100) AS PVP 
FROM PRODUCTO 
JOIN CATEGORIA ON PRODUCTO.CATEGORIA = CATEGORIA.ID;