-- 1
CREATE TABLE USUARIO (
    ID NUMBER,
    NOMBRE VARCHAR2(50 BYTE),
    APELLIDOS VARCHAR2(50 BYTE),
    TELEFONO VARCHAR2(12 BYTE),
    DIRECCION VARCHAR2(100 BYTE),
    CORREOE VARCHAR2(50 BYTE),
    USUARIOORACLE VARCHAR2(50 BYTE),
    TIPO VARCHAR2(35 BYTE) CHECK (TIPO IN ('GERENTE', 'ENTRENADOR', 'CLIENTE'))
) 
TABLESPACE TS_EX23
PCTFREE 25;

CREATE TABLE CLIENTE (
    ID NUMBER,
    OBJETIVO VARCHAR2(100),
    PREFERENCIAS VARCHAR2(100)
)
TABLESPACE TS_EX23
PCTFREE 25;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_EX23;
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE TS_EX23;

CREATE UNIQUE INDEX TR_USUARIOORACLE ON USUARIO(USUARIOORACLE) TABLESPACE TS_EX23;
CREATE INDEX TR_COMPLETO ON USUARIO(APELLIDOS, NOMBRE) TABLESPACE TS_EX23;
CREATE BITMAP INDEX TR_CARGO ON USUARIO(TIPO) TABLESPACE TS_EX23;
CREATE INDEX TR_TOTAL ON USUARIO(UPPER(APELLIDOS || NOMBRE)) TABLESPACE TS_EX23;

-- 2
GRANT DELETE ON USUARIO TO CESAR;
GRANT UPDATE (NOMBRE, APELLIDOS, CORREOE) ON USUARIO TO CESAR WITH GRANT OPTION;
CREATE VIEW VW_USUARIO AS SELECT ID, NOMBRE, APELLIDOS, CORREOE FROM USUARIO;
GRANT SELECT ON VW_USUARIO TO CESAR;
CREATE SYNONYM USUARIA FOR USUARIO;

-- 3
CREATE VIEW V_MIS_OBJETIVOS AS 
SELECT NOMBRE, APELLIDOS, OBJETIVO, PREFERENCIAS 
FROM USUARIO
JOIN CLIENTE ON USUARIO.ID = CLIENTE.ID
WHERE USUARIOORACLE = USER
WITH READ ONLY;

GRANT SELECT ON V_MIS_OBJETIVOS TO PUBLIC;

-- 4
CREATE MATERIALIZED VIEW VM_USUARIA
TABLESPACE TS_EX23
REFRESH FORCE NEXT SYSDATE + 3/24
AS SELECT ID, CORREOE, TIPO FROM USUARIO;
