-- Ejercicio 1
TRUNCATE TABLE MENSAJES;
TRUNCATE TABLE AUDITA_MENSAJES;

CREATE TABLE MENSAJES (
    Codigo NUMBER(20) PRIMARY KEY,
    Texto VARCHAR2(200)
);

CREATE TABLE AUDITA_MENSAJES (
    Quien VARCHAR2(20),
    Como VARCHAR2(20),
    Cuando DATE
);

CREATE OR REPLACE TRIGGER tr_audita_mensajes
AFTER INSERT OR DELETE OR UPDATE ON MENSAJES
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'INSERT', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'DELETE', SYSDATE);
    ELSE
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'UPDATE', SYSDATE);
    END IF;
END;
/

-- Ejercicio 2
ALTER TABLE MENSAJES ADD (
    Tipo VARCHAR2(30)
);

ALTER TABLE MENSAJES ADD CONSTRAINTS ck_tipo CHECK (Tipo in ('INFORMACION', 'RESTRICCION', 'ERROR', 'AVISO', 'AYUDA'));

INSERT INTO MENSAJES VALUES (1, 'Hola1', 'INFORMACION');
INSERT INTO MENSAJES VALUES (2, 'Hola2', 'INFORMACION');
INSERT INTO MENSAJES VALUES (3, 'Hola3', 'RESTRICCION');
INSERT INTO MENSAJES VALUES (4, 'Hola4', 'RESTRICCION');
INSERT INTO MENSAJES VALUES (5, 'Hola5', 'ERROR');
INSERT INTO MENSAJES VALUES (6, 'Hola6', 'ERROR');
INSERT INTO MENSAJES VALUES (7, 'Hola7', 'AVISO');
INSERT INTO MENSAJES VALUES (8, 'Hola8', 'AVISO');
INSERT INTO MENSAJES VALUES (9, 'Hola9', 'AYUDA');
INSERT INTO MENSAJES VALUES (10, 'Hola10', 'AYUDA');
COMMIT;

CREATE TABLE MENSAJES_Info (
    Tipo VARCHAR2(30)PRIMARY KEY,
    Cuantos_Mensajes NUMBER(2),
    Ultimo VARCHAR2(200)
);

INSERT INTO MENSAJES_Info SELECT Tipo, COUNT(*), NULL FROM MENSAJES GROUP BY Tipo;
COMMIT;

CREATE TRIGGER tr_mensajes_info
AFTER INSERT OR DELETE OR UPDATE ON MENSAJES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE MENSAJES_Info SET CUANTOS_MENSAJES = CUANTOS_MENSAJES + 1, ULTIMO = :NEW.TEXTO WHERE TIPO = :NEW.TIPO;
    ELSIF DELETING THEN
        UPDATE MENSAJES_Info SET CUANTOS_MENSAJES = CUANTOS_MENSAJES - 1, ULTIMO = NULL WHERE TIPO = :OLD.Tipo;
    ELSE
        IF :OLD.TIPO <> :NEW.TIPO THEN
            UPDATE MENSAJES_Info SET CUANTOS_MENSAJES = CUANTOS_MENSAJES - 1, ULTIMO = NULL WHERE TIPO = :OLD.TIPO;
            UPDATE MENSAJES_Info SET CUANTOS_MENSAJES = CUANTOS_MENSAJES + 1, ULTIMO = :NEW.TEXTO WHERE TIPO = :NEW.TIPO;
        ELSE
            UPDATE MENSAJES_Info 
            SET ULTIMO = :NEW.TEXTO 
            WHERE TIPO = :NEW.TIPO;
        END IF;
    END IF;
END;
/

-- Ejercicio 3
CREATE TABLE MENSAJES_TEXTO AS SELECT CODIGO, TEXTO FROM MENSAJES;
CREATE TABLE MENSAJES_TIPO AS SELECT CODIGO, TIPO FROM MENSAJES;
DROP TABLE MENSAJES;

CREATE VIEW VW_MENSAJES AS
SELECT TX.CODIGO, TX.TEXTO, TI.TIPO FROM MENSAJES_TEXTO TX JOIN MENSAJES_TIPO TI ON TX.CODIGO = TI.CODIGO;

SELECT * FROM VW_MENSAJES; 

/* Si sale lo mismo que antes. No deja hacer inserciones porque la vista depende de dos tablas y si añadimos algún dato no 
sabe a que tabla almacenar el dato. Se puede arreglar con un trigger que al insertar un valor a la vista se almacene en 
ambas tablas */

CREATE TRIGGER TR_MENSAJES
INSTEAD OF INSERT ON VW_MENSAJES
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES_TEXTO VALUES (:NEW.CODIGO, :NEW.TEXTO);
    INSERT INTO MENSAJES_TIPO VALUES (:NEW.CODIGO, :NEW.TIPO);
END;
/

-- Ejercicio 4
CREATE TABLE MENSAJES_BORRADOS (
    Codigo NUMBER(20) PRIMARY KEY,
    Texto VARCHAR2(200)
);

CREATE TRIGGER TR_MENSAJES_TEXTO
AFTER DELETE ON MENSAJES_TEXTO
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES_BORRADOS VALUES (:OLD.CODIGO, :OLD.TEXTO);
END;
/

-- Ejercicio 5
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        JOB_NAME => 'JOB_BORRAR_MENSAJES',
        JOB_TYPE => 'PLSQL_BLOCK',
        JOB_ACTION => 'BEGIN EXECUTE IMMEDIATE ''TRUNCATE TABLE MENSAJES_BORRADOS''; END;',
        START_DATE => SYSDATE,
        REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=2',
        ENABLED => TRUE,
        COMMENTS => 'Borra los mensajes borrados cada 2 minutos'
    );
END;
/

BEGIN
    DBMS_SCHEDULER.DROP_JOB(job_name => 'JOB_BORRAR_MENSAJES');
END;
/