project:
  type: book

book:
  title: "Mi primer libro en Quarto"
  author: "Miguel"
  date: "3/4/2026"
  chapters:
    - index.qmd
    - capitulo1.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



