## Ejercicio 1

Importa el dataset PREC_2021_Provincias.csv.
Como preprocesamiento:

- Coloca como nombre de las filas los valores de la columna region.
- Elimina las variables region, Parametro y anual.

Comprueba que sigues teniendo el valor de las provincias en el nombre de las filas del dataset.

Primera parte:

- Usar funciones apply para calcular el mes con mayor media de precipitación. (0.75 puntos)
- Selecciona un mes aleatoriamente. Para el mes seleccionado calcula la media de ese mes. (0.25 puntos)

Segunda parte:

- Para cada una de las provincias, calcular la precipitación media, máxima y el mes que llueve más. (0.75 puntos)
- Para cada una de los meses, decir la provincia con precipitación máxima. (0.75 puntos)
- Selecciona aleatoriamente una provincia. Calcular cuantas provincias tienen mayor precipitación en media que la precipitación media de la provincia selecionada. (0.5 puntos)

```{r}
library(tidyverse)
df <- read_delim("~/Desktop/uma-25-26-2/MCP/datasets/PREC_2021_Provincias.csv", delim = ";")
df <- as.data.frame(df)

rownames(df) <- df$region
df

df <- df |>
  select(-Parametro, -region, -anual)
df


```

