# Bloque 1: Análisis de Componentes Principales (PCA)

## Desarrollo del bloque

Una vez reducida la dimensionalidad, pasaremos a modelar el ecosistema de consumo como una red
compleja bidimensional.

### Carga de librerías

```{r}
#| message: false
library(tidygraph)
library(igraph)
library(ggraph)
library(ggforce)

set.seed(42)
```

### Creación del grafo

```{r}
coparticion <- df |>
  select(UserId, ProductId)

parejas_unicas <- coparticion |>
  inner_join(coparticion, by = "UserId", relationship = "many-to-many") |>
  filter(ProductId.x < ProductId.y) |>
  count(ProductId.x, ProductId.y, name = "weight") |>
  rename(from = ProductId.x, to = ProductId.y)
```

```{r}
calcular_densidad <- function(datos, umbral) {
  aristas_filtradas <- datos |> filter(weight >= umbral)
  
  g <- as_tbl_graph(aristas_filtradas, directed = FALSE)
  
  tibble(
    N = umbral,
    Densidad = edge_density(g) 
  )
}

tabla_densidad <- lapply(1:20, function(x) {
  calcular_densidad(parejas_unicas, x)
  }) |> 
  bind_rows()

tabla_densidad
```

```{r}
ggplot(tabla_densidad, aes(N, Densidad)) +
  geom_point(color = "blue") +
  geom_line(color = "red") +
  scale_x_continuous(breaks = 1:20) +
  labs(
    title = "Evolución de la densidad del grafo según el umbral N"
  ) +
  theme_minimal()
```


```{r}
N_usuarios <- 6
grafo <- as_tbl_graph(parejas_unicas |> filter(weight >= N_usuarios), directed = FALSE)
```

### Métricas de centralidad

```{r}
grafo <- grafo |>
  activate(nodes) |>
  mutate(
    Degree = centrality_degree(),
    PageRank = centrality_pagerank(weights = weight),
    Betweenness = centrality_betweenness(directed = FALSE)
  )
```

```{r}
print("Top productos por grado (VOLUMEN DE CO-COMPRA)")
grafo |> 
  activate(nodes) |> 
  as.data.frame() |>
  select(name, Degree) |> 
  arrange(desc(Degree)) |> 
  head(5)

print("Top productos faro(MAYOR INFLUENCIA)")
grafo |> 
  activate(nodes) |> 
  as.data.frame() |>
  select(name, PageRank) |> 
  arrange(desc(PageRank)) |> 
  head(5)

print("Top productos puente (CONECTORES DE CATEGORÍAS)")
grafo |> 
  activate(nodes) |> 
  as.data.frame() |>
  select(name, Betweenness) |> 
  arrange(desc(Betweenness)) |> 
  head(5)
```

### Detección de comunidades

```{r}
grafo <- grafo |>
  mutate(
    Louvain = as.factor(group_louvain()),
    Walktrap = as.factor(group_walktrap())
  )
```

```{r}
tibble(
  Algoritmo = c("Louvain", "Walktrap"),
  Modularidad = c(
    modularity(grafo, membership = as.numeric(V(grafo)$Louvain)),
    modularity(grafo, membership = as.numeric(V(grafo)$Walktrap))
  )
)
```

```{r}
metricas_comunidades <- metricas |>
  as.data.frame() |>
  rownames_to_column(var = "ProductId") |>
  inner_join(as_tibble(grafo), by = c("ProductId" = "name")) |>
  group_by(Louvain) |>
  summarise(
    productosDistintos = n_distinct(ProductId),
    ratingPromedio = round(mean(ratingPromedio), 2),
    numeroResenas = sum(numeroResenas),
    longitudResenaPromedio = round(mean(longitudResenaPromedio))
  ) |>
  arrange(desc(productosDistintos))

head(metricas_comunidades, 10)
```

### Visualización de comunidades

```{r}
grafo_limpio <- grafo |>
  activate(edges) |>
  filter(!edge_is_multiple(), !edge_is_loop()) |>
  activate(nodes) |>
  mutate(gradoInicial = centrality_degree()) |>
  filter(gradoInicial > 0)

top_comunidades <- metricas_comunidades |>
  arrange(desc(productosDistintos)) |>
  head(3) |>
  pull(Louvain)

grafo_plot <- grafo_limpio |>
  filter(Louvain %in% top_comunidades) |>
  activate(nodes) |>
  mutate(gradoSubgrafo = centrality_degree()) |>
  filter(gradoSubgrafo > 0)

ggraph(grafo_plot, layout = "nicely") +
  geom_mark_hull(
    aes(x = x, y = y, fill = Louvain, group = Louvain), 
    alpha = 0.15,          # Transparencia del relleno
    color = NA,            # Sin borde en la burbuja
    concavity = 10,        # Suavizado de la curva
    expand = unit(2, "mm") # Margen extra alrededor de los nodos
  ) +
  geom_edge_link(aes(width = weight), alpha = 0.15, color = "grey60") +
  scale_edge_width(range = c(0.2, 1.5)) +
  geom_node_point(aes(color = Louvain), size = 1.8, alpha = 0.8) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  theme_graph() +
  theme(legend.position = "none") +
  labs(
    title = "Visualización de las 3 mayores comunidades",
    color = "Comunidad"
  )
```

### Validación cruzada. PCA vs SNA

```{r}
productos <- metricas |>
  as.data.frame() |>
  rownames_to_column(var = "ProductId") |>
  mutate(
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2]
  ) |>
  inner_join(as_tibble(grafo), by = c("ProductId" = "name")) |>
  filter(Louvain %in% top_comunidades)

ggplot(productos, aes(x = PC1, y = PC2, color = Louvain)) +
  geom_point(alpha = 0.6, size = 1.8) + 
  scale_color_brewer(palette = "Set1") + 
  theme_minimal() +
  xlim(-1, 12) +
  ylim(-2, 30) +
  labs(
    title = "Validación Cruzada: proyección de comunidades SNA en el espacio PCA",
    x = "PC1",
    y = "PC2"
  ) +
  theme(
    legend.position = "bottom",
    plot.title = element_text(face = "bold", size = 14),
    panel.grid.minor = element_blank()
  )
```


